<a href="https://colab.research.google.com/github/dayananikol/CCMACLRL_EXERCISES_COM221ML/blob/main/exercise9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercise 9: Choosing the best performing model on a dataset

Instructions:

- Use the Dataset File to train your model
- Use the Test File to generate your results
- Use the Sample Submission file to generate the same format
- Use all classification models

Submit your results to:
https://www.kaggle.com/competitions/playground-series-s4e10/overview

In [763]:
import pandas as pd
import seaborn as sns
import numpy as np

from sklearn import metrics

from matplotlib import pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from sklearn.model_selection import cross_val_score, KFold

from sklearn import datasets

## Dataset File

In [764]:
dataset_url = 'https://github.com/robitussin/CCMACLRL_EXERCISES/blob/main/datasets/loan_approval/train.csv?raw=true'
df = pd.read_csv(dataset_url)

In [765]:
df.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,RENT,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,1,22,56000,OWN,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,2,29,28800,OWN,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,3,30,70000,RENT,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,4,22,60000,RENT,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0

In [766]:
df.tail()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
58640,58640,34,120000,MORTGAGE,5.0,EDUCATION,D,25000,15.95,0.21,Y,10,0
58641,58641,28,28800,RENT,0.0,MEDICAL,C,10000,12.73,0.35,N,8,1
58642,58642,23,44000,RENT,7.0,EDUCATION,D,6800,16.00,0.15,N,2,1
58643,58643,22,30000,RENT,2.0,EDUCATION,A,5000,8.90,0.17,N,3,0
58644,58644,31,75000,MORTGAGE,2.0,VENTURE,B,15000,11.11,0.20,N,5,0

In [767]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          58645 non-null  int64
 1   person_age                  58645 non-null  int64
 2   person_income               58645 non-null  int64
 3   person_home_ownership       58645 non-null  object
 4   person_emp_length           58645 non-null  float64
 5   loan_intent                 58645 non-null  object
 6   loan_grade                  58645 non-null  object
 7   loan_amnt                   58645 non-null  int64
 8   loan_int_rate               58645 non-null  float64
 9   loan_percent_income         58645 non-null  float64
 10  cb_person_default_on_file   58645 non-null  object
 11  cb_person_cred_hist_length  58645 non-null  int64
 12  loan_status                 58645 non-null  int64
dtypes: float64(3), int64(6), object(4)
memory usage: 5.8+ MB

In [768]:
df.sample(10)

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
4432,4432,27,125000,MORTGAGE,2.0,DEBTCONSOLIDATION,A,8000,6.03,0.06,N,7,0
23904,23904,30,60000,MORTGAGE,2.0,EDUCATION,D,10000,15.65,0.17,N,9,0
7088,7088,22,78000,MORTGAGE,6.0,VENTURE,A,10200,8.94,0.13,N,3,0
53023,53023,24,40000,RENT,0.0,PERSONAL,D,10000,16.00,0.25,N,3,0
198,198,28,95000,MORTGAGE,6.0,VENTURE,C,18000,13.79,0.19,N,8,0
30605,30605,26,34000,RENT,1.0,PERSONAL,C,1500,15.27,0.04,N,3,1
58397,58397,28,33000,RENT,2.0,EDUCATION,B,4000,11.71,0.12,N,6,0
37102,37102,23,80000,MORTGAGE,7.0,VENTURE,B,3000,12.21,0.04,N,2,0
53700,53700,23,60000,MORTGAGE,7.0,EDUCATION,C,8000,13.61,0.13,N,4,0
23840,23840,21,42500,RENT,3.0,DEBTCONSOLIDATION,C,7000,12.87,0.16,Y,2,0

In [769]:
df['person_home_ownership'].value_counts()

person_home_ownership
RENT        30594
MORTGAGE    24824
OWN          3138
OTHER          89
Name: count, dtype: int64

In [770]:
df['person_home_ownership'] = df['person_home_ownership'].map({'RENT': 0, 'MORTGAGE': 1, 'OWN':2, 'OTHER':3})
df.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,0,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,1,22,56000,2,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,2,29,28800,2,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,3,30,70000,0,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,4,22,60000,0,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0

In [771]:
df['loan_intent'].value_counts()

loan_intent
EDUCATION            12271
MEDICAL              10934
PERSONAL             10016
VENTURE              10011
DEBTCONSOLIDATION     9133
HOMEIMPROVEMENT       6280
Name: count, dtype: int64

In [772]:
df['loan_intent'] = df['loan_intent'].map({'EDUCATION': 0, 'MEDICAL': 1, 'PERSONAL':2, 'VENTURE':3, 'DEBTCONSOLIDATION':4, 'HOMEIMPROVEMENT':5})
df.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,0,0.0,0,B,6000,11.49,0.17,N,14,0
1,1,22,56000,2,6.0,1,C,4000,13.35,0.07,N,2,0
2,2,29,28800,2,8.0,2,A,6000,8.90,0.21,N,10,0
3,3,30,70000,0,14.0,3,B,12000,11.11,0.17,N,5,0
4,4,22,60000,0,2.0,1,A,6000,6.92,0.10,N,3,0

In [773]:
df['loan_grade'].value_counts()

loan_grade
A    20984
B    20400
C    11036
D     5034
E     1009
F      149
G       33
Name: count, dtype: int64

In [774]:
df['loan_grade'] = df['loan_grade'].map({'A': 0, 'B': 1, 'C':2, 'D':3, 'E':4, 'F':5, 'G':6})
df.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,0,0.0,0,1,6000,11.49,0.17,N,14,0
1,1,22,56000,2,6.0,1,2,4000,13.35,0.07,N,2,0
2,2,29,28800,2,8.0,2,0,6000,8.90,0.21,N,10,0
3,3,30,70000,0,14.0,3,1,12000,11.11,0.17,N,5,0
4,4,22,60000,0,2.0,1,0,6000,6.92,0.10,N,3,0

In [775]:
df['cb_person_default_on_file'].value_counts()

cb_person_default_on_file
N    49943
Y     8702
Name: count, dtype: int64

In [776]:
df['cb_person_default_on_file'] = df['cb_person_default_on_file'].map({'N': 0, 'Y': 1})
df.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,0,0.0,0,1,6000,11.49,0.17,0,14,0
1,1,22,56000,2,6.0,1,2,4000,13.35,0.07,0,2,0
2,2,29,28800,2,8.0,2,0,6000,8.90,0.21,0,10,0
3,3,30,70000,0,14.0,3,1,12000,11.11,0.17,0,5,0
4,4,22,60000,0,2.0,1,0,6000,6.92,0.10,0,3,0

In [777]:
df.drop(['id'], axis=1, inplace=True)
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,37,35000,0,0.0,0,1,6000,11.49,0.17,0,14,0
1,22,56000,2,6.0,1,2,4000,13.35,0.07,0,2,0
2,29,28800,2,8.0,2,0,6000,8.90,0.21,0,10,0
3,30,70000,0,14.0,3,1,12000,11.11,0.17,0,5,0
4,22,60000,0,2.0,1,0,6000,6.92,0.10,0,3,0

In [778]:
from sklearn.model_selection import train_test_split
x = df.drop("loan_status",axis=1)
y = df["loan_status"]

x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=1,test_size=0.3)

## Test File

In [779]:
test_url = 'https://github.com/robitussin/CCMACLRL_EXERCISES/blob/main/datasets/loan_approval/test.csv?raw=true'
dt=pd.read_csv(test_url)

In [780]:
dt.drop(['id'], axis=1, inplace=True)

In [781]:
dt['person_home_ownership'] = dt['person_home_ownership'].map({'RENT': 0, 'MORTGAGE': 1, 'OWN':2, 'OTHER':3})
dt['loan_intent'] = dt['loan_intent'].map({'EDUCATION': 0, 'MEDICAL': 1, 'PERSONAL':2, 'VENTURE':3, 'DEBTCONSOLIDATION':4, 'HOMEIMPROVEMENT':5})
dt['loan_grade'] = dt['loan_grade'].map({'A': 0, 'B': 1, 'C':2, 'D':3, 'E':4, 'F':5, 'G':6})
dt['cb_person_default_on_file'] = dt['cb_person_default_on_file'].map({'N': 0, 'Y': 1})
dt.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,23,69000,0,3.0,5,5,25000,15.76,0.36,0,2
1,26,96000,1,6.0,2,2,10000,12.68,0.10,1,4
2,26,30000,0,5.0,3,4,4000,17.19,0.13,1,2
3,33,50000,0,4.0,4,0,7000,8.90,0.14,0,7
4,26,102000,1,8.0,5,3,15000,16.32,0.15,1,4

In [782]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39098 entries, 0 to 39097
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  39098 non-null  int64
 1   person_income               39098 non-null  int64
 2   person_home_ownership       39098 non-null  int64
 3   person_emp_length           39098 non-null  float64
 4   loan_intent                 39098 non-null  int64
 5   loan_grade                  39098 non-null  int64
 6   loan_amnt                   39098 non-null  int64
 7   loan_int_rate               39098 non-null  float64
 8   loan_percent_income         39098 non-null  float64
 9   cb_person_default_on_file   39098 non-null  int64
 10  cb_person_cred_hist_length  39098 non-null  int64
dtypes: float64(3), int64(8)
memory usage: 3.3 MB

## Sample Submission File

In [783]:
sample_submission_url ='https://github.com/robitussin/CCMACLRL_EXERCISES/blob/main/datasets/loan_approval/sample_submission.csv?raw=true'

sf=pd.read_csv(sample_submission_url)

In [784]:
sf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39098 entries, 0 to 39097
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           39098 non-null  int64
 1   loan_status  39098 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 611.0 KB

In [785]:
print(sf.columns)

Index(['id', 'loan_status'], dtype='object')

## 1. Train a KNN Classifier

In [786]:
score_list = {}

In [787]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=22) #I've tried more than 50 values. 22 is the best value

KNN.fit(x_train,y_train)
knn_score = KNN.score(x_test,y_test)
print(f"Score is {knn_score}")

Score is 0.8932590655905422

In [788]:
# y_true = y_test
# y_pred = KNN.predict(x_test)
# plot_confusionMatrix(y_true,y_pred)

- Perform cross validation

In [789]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(KNN, x, y, cv=5)
scores

array([0.89368233, 0.89257396, 0.89402336, 0.89282974, 0.89240344])

In [790]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.89 accuracy with a standard deviation of 0.00

In [791]:
score_list["KNN Classifier"] = scores.mean()

## 2. Train a Logistic Regression Classifier

In [792]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(x_train,y_train)

lr_score = LR.score(x_test,y_test)


print(f"Score is {lr_score}")

Score is 0.8845629191769921

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

- Perform cross validation

In [793]:
scores = cross_val_score(LR, x, y, cv=5)
scores

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([0.88387757, 0.88532697, 0.88362179, 0.88345127, 0.88626481])

In [794]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.88 accuracy with a standard deviation of 0.00

In [795]:
score_list["Logistic Regression"] = scores.mean()

## 3. Train a Naive Bayes Classifier

In [796]:
from sklearn.naive_bayes import GaussianNB

nbc = GaussianNB()
nbc.fit(x_train,y_train)
nbc_score = nbc.score(x_test,y_test)

print(f"Score is {nbc_score}")

Score is 0.8848471069682846

- Perform cross validation

In [797]:
scores = cross_val_score(nbc, x, y, cv=5)
scores

array([0.88140506, 0.88541223, 0.88583852, 0.8871174 , 0.88490067])

In [798]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.88 accuracy with a standard deviation of 0.00

In [799]:
score_list["GaussianNBC"] = scores.mean()

## 4. Train a SVM Classifier

In [800]:
svc = SVC()
svc.fit(x_train,y_train)
svc_score = svc.score(x_test,y_test)
print(f"Score is {svc_score}")

Score is 0.8579061043537569

- Perform cross validation

In [801]:
scores = cross_val_score(svc, x, y, cv=5)
scores

array([0.85761787, 0.85761787, 0.85761787, 0.85753261, 0.85761787])

In [802]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.86 accuracy with a standard deviation of 0.00

In [803]:
score_list["SVC"] = scores.mean()

## 5. Train a Decision Tree Classifier

In [804]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=1)
dtc.fit(x_train,y_train)

dtc_score = dtc.score(x_test,y_test)
print(f"Score is {dtc_score}")

Score is 0.9119017846993294

- Perform cross validation

In [805]:
scores = cross_val_score(dtc, x, y, cv=5)
scores

array([0.91226874, 0.90996675, 0.91422969, 0.91559383, 0.91278029])

In [806]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.91 accuracy with a standard deviation of 0.00

In [807]:
score_list["DTC"] = scores.mean()

## 6. Train a Random Forest Classifier

In [808]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=50,random_state=1)
rfc.fit(x_train,y_train)
rfc_score = rfc.score(x_test,y_test)
score_list["RFC"]=rfc_score

print(f"Score is {rfc_score}")

Score is 0.9509491872229169

## 7. Compare all the performance of all classification models

In [809]:
score_list = list(score_list.items())

In [810]:
for alg,score in score_list:
    print(f"{alg} Score is {str(score)[:4]} ")

KNN Classifier Score is 0.89
Logistic Regression Score is 0.88
GaussianNBC Score is 0.88
SVC Score is 0.85
DTC Score is 0.91
RFC Score is 0.95

## 9. Generate Submission File

Choose the model that has the best performance to generate a submission file.

In [811]:
id = sf.pop('id')
y_pred = rfc.predict(dt)

# Create a submission DataFrame
submission_df = pd.DataFrame({
    'id': id,
    'loan_status': y_pred
})

# Save the submission DataFrame to a CSV file
submission_df.to_csv('submission_file.csv', index=False)
print("Submission file created: submission_file.csv")

Submission file created: submission_file.csv